### ISSUE TITLE
Error: ok (200) while importing

### ISSUE THREAD

**Issue by themenow** [awesomemotive/one-click-demo-import#112]
Hi,

I got a strange error during importing, as the title says

> Error: ok (200)

And the cause was, by looking into the ajax response

```
<br />
<b>Warning</b>:  set_time_limit() has been disabled for security reasons in <b>/usr/home/maliboo.tv/web/wp-content/plugins/one-click-demo-import/inc/Importer.php</b> on line <b>122</b><br />
{"status":"newAJAX","message":"Time for new AJAX request!: 27.420871973038"}
```

PHP limits is enough for importing demo data, still it failed due to the set_time_limit issue.

**Comment by kamiyeye** [comment]
A possible fix to the issue:

Add checking for PHP safe mode and disabled php before call set_time_lime

```
		// Increase PHP max execution time. Just in case, even though the AJAX calls are only 25 sec long.
		$disabled = explode(',', ini_get('disable_functions'));
  		if( !ini_get('safe_mode') && !in_array('set_time_limit', $disabled) ) {
	  		set_time_limit( apply_filters( 'pt-ocdi/set_time_limit_for_demo_data_import', 300 ) );
	  	}
```

inc/importer.php

**Comment by capuderg** [comment]
Hi,

this is a strange issue yes... Thanks for providing a solution for it.

I'll take a closer look add it to the plugin for the next version.

Take care!

**Comment by beachgrrrl** [comment]
Hi @capuderg , did you add a fix for this in the latest version of OCDI? I have a customer trying to install one of my themes that got this error.

**Comment by capuderg** [comment]
Hi @beachgrrrl,

no, I'm sorry, this is still not in the plugin.

Could you please edit the plugin on the customer's site with the code change suggested above and let me know, if that solve the OK 200 error? It would be great to have another test, before adding this to the plugin.

If this works for you as well, then I'll be adding this to the plugin and update it.

Again, I'm sorry, I forgot about this issue...

Take care!

**Comment by beachgrrrl** [comment]
Thanks as always for your help! Somehow he got it to work - he says “The problem has already been solved surely with a small #” I don’t know what that means! There is a bit of a language barrier, he is Spanish, but anyways, I did not have a chance to get into his site. But I will let you know if I come across anyone else with this issue. Joan

**Comment by capuderg** [comment]
Hi everyone,

sorry for the late reply.

This is now fixed and will be available in the next plugin update.

Have a nice day!
