### ISSUE TITLE
Feature Request: Choose able Dummy Data

### ISSUE THREAD

**Issue by Uranbold** [awesomemotive/one-click-demo-import#120]
Hi guys,

Thanks for awesome plugin and I am wondering if you guys add future release with Choosing which Custom Post Type or Which Posts or Which Pages etc something like similar to this -> https://support.undsgn.com/hc/en-us/article_attachments/208847509/doc-import-new.jpg

This is really helpful for lots of authors.

Thanks.

**Comment by capuderg** [comment]
Hi,

thanks for opening this feature request. We will keep this in mind, when making plans for future plugin versions.

Have a nice day!

**Comment by Uranbold** [comment]
Bump man :)

Thanks for the awesome plugin. We need to Select which Posts or which Pages Specially and then this plugin will be Pure Gold!

Thanks.

**Comment by capuderg** [comment]
Hi @Uranbold,

I'm sorry, there are currently no plans to add this to the plugin.

If you are interested, you can prepare a pull-request and I can review it (and merge it), if it will function correctly and meet our standards.

Have a nice day!

**Comment by capuderg** [comment]
Hi,

There are currently no plans to allow the user to specifically select which pages/posts/CPT to import from the XML file.

This would mean, that we would first have to parse the XML file, filter out certain "categories" and then allow the user to cherry-pick which one to import. This would not follow our vision of making the Theme demo import very straightforward for the end-user.

I'm closing this GH issue for now.

P.S.: We will be adding the feature to install recommended/required plugins in the import flow in the upcoming plugin update. And also allow users to import single predefined demo pages (contact, FAQ, about us, ...).
