### ISSUE TITLE
Fatal error: Cannot redeclare class OCDI_Plugin on line 21

### ISSUE THREAD

**Issue by BygoneGh** [awesomemotive/one-click-demo-import#133]
I have been using my One Click Demo Importer for quite some time now, but recently I tried to update it and activate it and it gave me an error feedback "Fatal error: Cannot redeclare class OCDI_Plugin in import.php on line 21". Kindly see Line 21 below

class OCDI_Plugin {
	/**
	 * Constructor for this class.
	 */
	public function __construct() {
		/**
		 * Display admin error message if PHP version is older than 5.3.2.
		 * Otherwise execute the main plugin class.
		 */
		if ( version_compare( phpversion(), '5.3.2', '<' ) ) {
			add_action( 'admin_notices', array( $this, 'old_php_admin_error_notice' ) );
		}
		else {
			// Set plugin constants.
			$this->set_plugin_constants();

			// Composer autoloader.
			require_once PT_OCDI_PATH . 'vendor/autoload.php';

			// Instantiate the main plugin class *Singleton*.
			$pt_one_click_demo_import = OCDI\OneClickDemoImport::get_instance();

			// Register WP CLI commands
			if ( defined( 'WP_CLI' ) && WP_CLI ) {
				WP_CLI::add_command( 'ocdi list', array( 'OCDI\WPCLICommands', 'list_predefined' ) );
				WP_CLI::add_command( 'ocdi import', array( 'OCDI\WPCLICommands', 'import' ) );
			}
		}
	}

	/**
	 * Display an admin error notice when PHP is older the version 5.3.2.
	 * Hook it to the 'admin_notices' action.
	 */
	public function old_php_admin_error_notice() {
		$message = sprintf( esc_html__( 'The %2$sOne Click Demo Import%3$s plugin requires %2$sPHP 5.3.2+%3$s to run properly. Please contact your hosting company and ask them to update the PHP version of your site to at least PHP 5.3.2.%4$s Your current version of PHP: %2$s%1$s%3$s', 'pt-ocdi' ), phpversion(), '<strong>', '</strong>', '<br>' );

		printf( '<div class="notice notice-error"><p>%1$s</p></div>', wp_kses_post( $message ) );
	}

	/**
	 * Set plugin constants.
	 *
	 * Path/URL to root of this plugin, with trailing slash and plugin version.
	 */
	private function set_plugin_constants() {
		// Path/URL to root of this plugin, with trailing slash.
		if ( ! defined( 'PT_OCDI_PATH' ) ) {
			define( 'PT_OCDI_PATH', plugin_dir_path( __FILE__ ) );
		}
		if ( ! defined( 'PT_OCDI_URL' ) ) {
			define( 'PT_OCDI_URL', plugin_dir_url( __FILE__ ) );
		}

		// Action hook to set the plugin version constant.
		add_action( 'admin_init', array( $this, 'set_plugin_version_constant' ) );
	}

	/**
	 * Set plugin version constant -> PT_OCDI_VERSION.
	 */
	public function set_plugin_version_constant() {
		if ( ! defined( 'PT_OCDI_VERSION' ) ) {
			$plugin_data = get_plugin_data( __FILE__ );
			define( 'PT_OCDI_VERSION', $plugin_data['Version'] );
		}
	}
}

**Comment by capuderg** [comment]
Hi,

are you using it as a plugin or did you add it to your theme?

The strange thing here is, that in your error it says: `in import.php on line 21`. Our plugin does not have an `import.php` file... Please check your theme and other plugins you have active, to see, if there are any duplicates, which use our plugin code...

Take care!

**Comment by BygoneGh** [comment]
Thank you for your Time Capuderg, can you please help me with the easiest way to get that code out of my settings.

**Comment by capuderg** [comment]
Hi @BygoneGh,

I'm not sure I understand, what your problem is... 

Are you a theme author that is using the OCDI plugin code directly in your theme and you want to remove it now?

Or are you a theme user, which uses our OCDI plugin (in manual mode) on different themes and are not using a theme, which uses OCDI plugin code directly in the theme code?

Take care!
