### ISSUE TITLE
Wrong URL on switch import mode link when using custom admin menu

### ISSUE THREAD

**Issue by daviedR** [awesomemotive/one-click-demo-import#135]
Hi there,

Your `Switch to Manual Import!` and the `Switch back to theme predefined imports!` link seems to have wrong URL when `parent_slug` is configured to a custom admin menu slug. If you define the `parent_slug` to be a slug of your custom admin page, e.g. `mytheme`, the link would be:

```
http://mydomain.com/wp-admin/mytheme?page=pt-one-click-demo-import&import-mode=manual
```

where it should be:

```
http://mydomain.com/wp-admin/admin.php?page=pt-one-click-demo-import&import-mode=manual
```

Please help.

**Comment by capuderg** [comment]
Hi @daviedR,

thank you for reporting this bug. We will look into it and fix it as soon as possible.

Take care!

**Comment by capuderg** [comment]
Hi @daviedR,

sorry for the late reply.

This issue was fixed and will be available in the next plugin update.

Have a nice day!
