### ISSUE TITLE
Option Tree integration

### ISSUE THREAD

**Issue by shofer4eto** [awesomemotive/one-click-demo-import#136]
Anyone adopted option tree into the import plugin that would be kind enough to share their code?
Thanks! :)

**Comment by capuderg** [comment]
Hi @shofer4eto,

sorry for the late reply.

If this is still relevant, a user already posted how to integrate the Option Tree with our plugin. More info here: https://github.com/awesomemotive/one-click-demo-import/issues/95

Have a nice day!
