### ISSUE TITLE
set_time_limit() Security issue

### ISSUE THREAD

**Issue by anteksiler** [awesomemotive/one-click-demo-import#144]
One of my clients is getting the following error:

`Warning: set_time_limit() has been disabled for security reasons.`

This causes the ajax calls to stop. Is there anyway to change it that it does not stop the import process?

**Comment by capuderg** [comment]
Hi,

I've never came across such server configuration, so It would really help me out, if you could test something on this server:

Could you please edit our plugin on the clients server and change [this line](https://github.com/proteusthemes/one-click-demo-import/blob/f0e60fa8437fcb9cbb991a12f58a04ff21f7b72a/inc/Importer.php#L121):

`set_time_limit( apply_filters( 'pt-ocdi/set_time_limit_for_demo_data_import', 300 ) );`

To this:

```
if ( strpos( ini_get( 'disable_functions' ), 'set_time_limit' ) === false ) {
  set_time_limit( apply_filters( 'pt-ocdi/set_time_limit_for_demo_data_import', 300 ) );
}
```

Let me know, if this check is working OK, so we can add it to the plugin.

Take care!

**Comment by anteksiler** [comment]
I am trying to change the lines using WordPress theme editor, but it does not let me change those lines, as it says "_Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP._". 

Also tried the solution given here: https://github.com/proteusthemes/one-click-demo-import/issues/112#issuecomment-311998754

I'll ask the customer for FTP details.

**Comment by anteksiler** [comment]
Yeap, after changing from the FTP, your solution is working.

**Comment by capuderg** [comment]
Hi everyone,

sorry for the late reply.

This is now fixed and will be available in the next plugin update.

Have a nice day!
