### ISSUE TITLE
WP Cli Compatibility With Elementor and Others Plugins

### ISSUE THREAD

**Issue by HW-Siew** [awesomemotive/one-click-demo-import#157]
If we use ocdi to import content of an Elementor page via wp cli, the imported content fail to maintaine its original structure. Please refer to issue https://github.com/pojome/elementor/issues/4891.

After some digging, it seems to be a constant 'WP_LOAD_IMPORTERS' is not defined at the time cli is running for WP_Importer.

**Comment by capuderg** [comment]
Hi,

I'm sorry, but we do not use Elementor, so we are not familiar with how it works. As I see, they guys at Elementor are working on a fix for this.

As I understand the default WP importer CLI commands do not work as well...

If Elementor team will not be able to solve this issue on their own, we would welcome a PR on our plugin, for fixing this problem.

Take care!

**Comment by capuderg** [comment]
Hi @HW-Siew,

sorry for the late reply.

I've tested the import with our `import` WP CLI command with an exported Elementor page and everything looked the same as importing it with OCDI interface importer or the original Elementor page.

If this is still relevant, could you please provide an XML import file (and other import files) that would produce the wrong import via the WP CLI import. And an example (original page) as to how it should look like.

I used the latest version of Elementor. Did they maybe fix it already?

For now, I'm closing this GH issue.

Take care!
