### ISSUE TITLE
How to prevent the after_import and after_content_import_execution for Manual demo files upload?

### ISSUE THREAD

**Issue by shofer4eto** [awesomemotive/one-click-demo-import#162]
I have several custom methods get called with the hooks after the content import.
For example: 
after_content_import_execution -> I import Option tree theme options.
after_import -> I set the home page, set the main menu etc.

I noticed that if using the Manual demo files upload for importing only widgets for example still executes the above actions so I end up not only uploading manually a single file but the actions I have set to the hooks. How do I prevent that? Thanks!

**Comment by capuderg** [comment]
Hi,

but you still have predefined demo imports on this theme, right? That's why the after import hooks are triggered.

Take care!
