### ISSUE TITLE
progress bar

### ISSUE THREAD

**Issue by Pixelous** [awesomemotive/one-click-demo-import#166]
Hi,

can you please add progress bar? Perhaps grab the code from WordPress Importer Redux https://github.com/humanmade/WordPress-Importer ?

**Comment by capuderg** [comment]
Hi,

there are currently no plans to add a progress bar. It would require the use of newer technologies (that will not work for some of the end-users) or it would require to first process the importing files to get the basic info and that would mean more server resources and time on an already resource/time heavy operation.

I'm closing this issue for now.
