### ISSUE TITLE
Import only if the website is just plain can not import second one...

### ISSUE THREAD

**Issue by Christianzimpel** [awesomemotive/one-click-demo-import#167]
If Wordpress is just fresh the import work like a charme. 
But if I have content on the site,  it say's the import ist done...  But its not. 
Can I only import to brand new Wordpress Sites without any content?

**Comment by capuderg** [comment]
Hi,

yes, the demo content import will work best, if the WP site is fresh... However it should work OK as well, if you have existing content. 

It actually depends on what kind of existing content you have, if it's the same as the demo import content (same post/page slugs and titles), then the import might clash with existing content...

**Comment by capuderg** [comment]
Hi,

yes, the demo content import will work best, if the WP site is fresh... However it should work OK as well, if you have existing content. 

It actually depends on what kind of existing content you have, if it's the same as the demo import content (same post/page slugs and titles), then the import might clash with existing content...

**Comment by spartac** [comment]
True.I have tested it and it works just fine with fresh install.
but it's important in case of a theme with several demos , the same content but different widgets for example.
