### ISSUE TITLE
Problem with widgets and customizer imports

### ISSUE THREAD

**Issue by laracatalan08** [awesomemotive/one-click-demo-import#172]
Hello. I need urgent help. I was trying for so long to add widgets and customizer data on code like the plugin One Click Demo Import indicates. I have the files at ocdi folder on server, I logged in by FTP, created it and loaded the files here. So I have this code on my configuration, that I think it's correct:
...
 'import_file_name'             => 'Andreina Theme - Demo',
      'categories'                   => array( 'Blogging', 'Social Media' ),
      'local_import_file'            => trailingslashit( get_template_directory() ) . 'ocdi/demo-content.xml',
      'local_import_widget_file'     => trailingslashit( get_template_directory() ) . 'ocdi/widgets.json',
      'local_import_customizer_file' => trailingslashit( get_template_directory() ) . 'ocdi/customizer.dat',
      'local_import_redux'           => array(
        array(
          'file_path'   => trailingslashit( get_template_directory() ) . 'ocdi/redux.json',
          'option_name' => 'redux_option_name',
        ),
      ),
      'import_preview_image_url'     => 'https://demo-andreina.marketinglife.es/wp-content/uploads/2018/11/screenshot.jpg',
      'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'your-textdomain' ),
      'preview_url'                  => 'https://demo-andreina.marketinglife.es/',
    ),
...
I haven't got redux files (I don't know if they are necessary, please confirm me it). But the fact is when I want to import demo in a new website, the widgets and customizer don't run, the same with the website fonts... Appears the following error:

---Importing widgets---
Error: Widget import data could not be read. Please try a different file.

---Importing customizer settings---
Error: The customizer import file is not suitable for current theme. You can only import customizer settings for the same theme or a child theme.

Would you help me please? I will be so grateful cause It's driving me crazy -.-
Thank you so much!

**Comment by pavlyukpetr** [comment]
I have the same error with the Widget import.

**Comment by DeoThemes** [comment]
Change file extension from **ocdi/widgets.json** to **ocdi/widgets.wie**

**Comment by sbnoman01** [comment]
Hey laracatalan08, Are you able to fix the issue? My customizer is not importing it says "customizer import file is not suitable for current theme ... "
