### ISSUE TITLE
Trying to Fix 500 internal error (PHP version)

### ISSUE THREAD

**Issue by chafikgharbi** [awesomemotive/one-click-demo-import#174]
When I import demo data (Widgets data) I get 500 internal error, I figured out that this problem is due to php version I don't know if someone tested it in PHP7.2

What did to fix that:

I added this line before line 250 /inc/Widgetimporter.php file
`$sidebars_widgets = !empty($sidebars_widgets) ? $sidebars_widgets : array();`

We can't put data in an empty string variables:
`$sidebars_widgets[ $use_sidebar_id ][] = $new_instance_id;`

**Comment by yoganow** [comment]
I'm having this same issue. Can I pay you to fix this for me?

**Comment by chafikgharbi** [comment]
@yoganow If you have the same issue then I will fix it for you without any charge, Send me more details.

**Comment by b15h0y** [comment]
I am facing the same error while importing demos. any solutions regarding this?

**Comment by capuderg** [comment]
Hi all,

this issue was fixed in the plugin code and will be available in the next plugin update.

Thanks for reporting it and have a nice day!
