### ISSUE TITLE
Fatal error: Cannot declare class OCDI_Plugin, because the name is already in use in ... on line 21

### ISSUE THREAD

**Issue by ideasmart** [awesomemotive/one-click-demo-import#175]
Installed Elevation Wordpress theme and installed Candor Framework. but when installing, following error appears 

Plugin could not be activated because it triggered a fatal error

Fatal error: Cannot declare class OCDI_Plugin, because the name is already in use in /home/ideactto/www.domain.org/wp-content/plugins/candor-framework/lib/demo-importer/one-click-demo-import.php on line 21

Please need help

**Comment by capuderg** [comment]
Hi @ideasmart,

sorry for the late reply.

It looks like the Condor Framework is including our plugin (OCDI) in their plugin codebase. I think they should add a check if our plugin is installed and not include their version of OCDI or at least prefix the namespace of their version of the OCDI code.

If this is still relevant, please contact their support and suggest those solutions.

Take care!
