### ISSUE TITLE
Error: parsererror (200)

### ISSUE THREAD

**Issue by helvetica123** [awesomemotive/one-click-demo-import#193]
this is my function.php script:

```
// Load any external files you have here
function ocdi_import_files() {
  return array(
    array(
      'import_file_name'             => 'Demo Import 1',
      'categories'                   => array( 'Category 1', 'Category 2' ),
      'local_import_file'            => trailingslashit( get_template_directory() ) . 'demo/sanayi-deniztasarm.WordPress.2019-07-16.xml',

      'import_preview_image_url'     => trailingslashit( get_template_directory() ) . 'demo/demo.jpg',
      'import_notice'                => __( 'After you import this demo, you will have to setup the slider separately.', 'your-textdomain' ),
      'preview_url'                  => 'http://www.your_domain.com/my-demo-1',
    ),

  );
}
add_filter( 'pt-ocdi/import_files', 'ocdi_import_files' );
```

and this is the error:

Error: parsererror (200)

the xml include elementor pages and some pages need different plugins/addons but i didnt install them before importing

**Comment by helvetica123** [comment]
i change the xml with no need different plugin but plugin still gives the error

**Comment by capuderg** [comment]
Hi @helvetica123,

sorry for the late reply.

Was your XML file valid? Did you try to open it in a browser? Usually, if it's corrupted, the browser will let you know on which line, and you can inspect and fix it. Maybe there was an invalid character in the file and that's why you got the parse error.

Take care!

**Comment by pablodiloreto** [comment]
Hello Team! The problem is not with vLog, is with "Redux Framework plugin".
