### ISSUE TITLE
Warning: set_time_limit() has been disabled for security reasons in /home/vol11_1/epizy.com/epiz_24482915/htdocs/wp-content/plugins/wordpress-importer/wordpress-importer.php on line 89

### ISSUE THREAD

**Issue by raynknight** [awesomemotive/one-click-demo-import#196]
Warning: set_time_limit() has been disabled for security reasons in /home/vol11_1/epizy.com/epiz_24482915/htdocs/wp-content/plugins/wordpress-importer/wordpress-importer.php on line 89 plz help me to fix this I have free web hosting by infinityfree

**Comment by capuderg** [comment]
Hi @raynknight,

this is a repository for One Click Demo Import plugin and it looks like you were using the WordPress Importer plugin. Please contact support for that particular plugin.

Take care!
