### ISSUE TITLE
Contact form7 is not getting the right one & Hello World post is not removed.

### ISSUE THREAD

**Issue by codepixar** [awesomemotive/one-click-demo-import#197]
I am using the most popular 'One click demo import' WordPress plugin for a long time. It's really very powerful plugin, love it. But, I face some problems after importing 'Demo data'. The 'Contact form7' is not getting the right one when there are multiple forms & the 'Hello World' post is not removed, as a result it's ugly to show without a featured image.

Can you please help me? I'm looking forward to hearing from you.

Thanks

**Comment by capuderg** [comment]
Hi @codepixar,

Sorry for this late reply.

Our plugin is non-destructive (it will not delete content on its own). If you want to configure something after the import is finished, you can do so with custom code in the after import hook: `pt-ocdi/after_import`. Please read more on how to use [this hook here](https://github.com/awesomemotive/one-click-demo-import#how-to-automatically-assign-front-page-posts-page-and-menu-locations-after-the-importer-is-done).

The example there is not exactly what you need, but you'll be able to change the code to delete a Hello World post or any other plugin configurations.

Take care!
