### ISSUE TITLE
Invalid URL on readme.md

### ISSUE THREAD

**Issue by murshed** [awesomemotive/one-click-demo-import#201]
> 
> Are you a theme author?
> 
> Setup One Click Demo Imports for your theme and your users will thank you for it!
> 
> Follow this easy guide on how to setup this plugin for your themes!
> 
> Also sign up to the newsletter, so we can inform you about any updates, changes or improvements.
> 
> Are you a theme user?
> 
> Contact the author of your theme and let them know about this plugin. Theme authors can make any theme compatible with this plugin in 15 minutes and make it much more user-friendly.
> 
> "Where can I find the contact of the theme author?"
> 
> This plugin will create a submenu page under Appearance with the title Import demo data.

Readme.md http://proteusthemes.github.io/one-click-demo-import/theme-users.html

**Comment by capuderg** [comment]
Hi,

thank you very much for letting us know that the documentation page is not working.

We will fix the links in the next plugin update. And you can find the link to the correct docs page here: http://awesomemotive.github.io/one-click-demo-import/index.html

Thank you and have a nice day!
