### ISSUE TITLE
Import complete but nothing imported

### ISSUE THREAD

**Issue by hackytricks** [awesomemotive/one-click-demo-import#202]
Hello, 
i am using localhost, i tried importing several times, it waits for sometime and then says import done but when i tried to check there is nothing imported. 

When i am using a domain site to import demo contents its returning an error: Error 520: Origin Error.

The author has not given any manual import contents so the only way i can import data is through demo import.

**Comment by capuderg** [comment]
Hi @hackytricks,

Sorry for the late reply.

Our plugin just imports the content given/defined by the theme authors, so if the content is not being imported, please contact the theme support. They should be able to help you out with your demo content.

Have a nice day!
