### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by shooenook** [awesomemotive/one-click-demo-import#204]
Hi,

There's a PHP notice if the current theme doesn't define the import files, in case of a manual import:

`PHP Notice:  Undefined offset: 0 in wp-content\plugins\one-click-demo-import\inc\ImportActions.php on line 124`

I guess some kind of "isset(..." would resolve this. Thanks for your time!

**Comment by capuderg** [comment]
Hi,

this fix will be available in the next plugin update.

Thank you for reporting it!

Have a nice day!

**Comment by capuderg** [comment]
The plugin was just updated (v2.6.0).

Could you please check if this issue is now resolved?

Thank you and have a nice day!

**Comment by hivepress** [comment]
Thanks for fixing this, seems to be ok now.

**Comment by shooenook** [comment]
Thanks for fixing this, seems to be ok now.

**Comment by capuderg** [comment]
@shooenook thank you for verifying! :)
