### ISSUE TITLE
The theme author tutorial page doesn't works

### ISSUE THREAD

**Issue by acleyfilho** [awesomemotive/one-click-demo-import#208]
Hello,
I'm trying to access the link http://proteusthemes.github.io/one-click-demo-import/ and doesn't works

**Comment by capuderg** [comment]
Hi,

thank you very much for letting us know that the documentation page is not working.

We will fix the links in the next plugin update. And you can find the link to the correct docs page here: http://awesomemotive.github.io/one-click-demo-import/index.html

Thank you and have a nice day!
