### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by trimalcione** [awesomemotive/one-click-demo-import#214]
Hello,

after two hours of importing it gives me `Error: error(0)` without returning any error in the logs. I tried two times with the files below. I just visited [docs](https://github.com/awesomemotive/one-click-demo-import/blob/master/docs/import-problems.md) but without success. Could you help me please? Thank you very much.

Here are the files, notice that I added .txt extension just for uploading the files on this post:
[khelo-content.xml.txt](https://github.com/awesomemotive/one-click-demo-import/files/5033999/khelo-content.xml.txt)
[khelo-widget.wie.txt](https://github.com/awesomemotive/one-click-demo-import/files/5034002/khelo-widget.wie.txt)

**Comment by capuderg** [comment]
Hi,

are you a theme author trying to configure our plugin for your theme? Or are you a user of a theme that uses our One Click Demo Import plugin?

Is this a free theme, that we can use to import the demo data with?

**Comment by trimalcione** [comment]
Sorry, it was an issue due to the hosting service.

**Comment by capuderg** [comment]
I'm glad you resolved your issue. Could you please let us know what the issue was and how you resolved it? So others with similar issues could maybe find the solution here. Thanks! :)

**Comment by trimalcione** [comment]
The hosting service is OVH, which enables firewall and security policies by default, blocking every request. I switched from production to development environment and it worked!
