### ISSUE TITLE
Remove ProteusThemes references

### ISSUE THREAD

**Issue by jaredatch** [awesomemotive/one-click-demo-import#215]
See https://a.cl.ly/kpubwbQ5 and https://a.cl.ly/WnuJrJdn

@mattbrett will be reaching out to you with new banner and icon assets.

In the `by XXX` below the plugin header, update to One Click Demo Import user (https://profiles.wordpress.org/ocdi/). In the `Contributors & Developers` section it should read as One Click Demo Import, Syed Balki, Jared Atchison, and Gregor Capedur (if you'd like).

Once these changes are done, I believe you should be able to roll them out without tagging a release, @slaFFik can likely confirm this.

Thanks!

**Comment by slaFFik** [comment]
Yes, updating `readme.txt` in `trunk` is fine without a release. WP.org will pick up the changes in up to 10 minutes and it should start displaying new information on WP.org.

**Comment by mattbrett** [comment]
Sent new assets to @capuderg via Slack.

**Comment by capuderg** [comment]
Thanks everyone!

I've updated the trunk and assets folder. It looks like the assets updated instantly, but the `by XXX` and the contributors did not update yet. I'll wait a few minutes and if it does not update, I'll push the changes to the current version tag as well (I updated readme.txt and the main plugin file header). That shouldn't cause any issue right? It's not a code change.

@jaredatch there are a lot of references to ProteusThemes in the actual plugin code, but I guess we'll tackle that some other time :)

**Comment by jaredatch** [comment]
Given the install base, and the previous issue editing an existing tag caused, I'd just wait until next update. If it becomes an issue we can do that in a pinch, but hopefully that won't be the case. Perhaps a reason for a minor update will arise before the next big planned update.

**Comment by capuderg** [comment]
I've removed all ProteusThemes references (PT named variables, constants, URLs, ...) in the `refresh-3.0` branch and kept a few because of backward compatibility.

The assets and readme.txt was updated already, so I'm closing this GH issue. And the changes will be live with the next plugin version.
