### ISSUE TITLE
Store failed media imports and skip them in next AJAX calls

### ISSUE THREAD

**Issue by capuderg** [awesomemotive/one-click-demo-import#216]
WP.org ticket: https://wordpress.org/support/topic/one-click-import-no-longer-working/

## Expected:
The plugin should store the failed media imports and check on subsequent AJAX calls if the media should be skipped. This would prevent endless cycle of trying to import the same failing media on each AJAX call.

## Current:
The plugin tries to import media files on each AJAX request, which means a couple of missing/broken images (or server restrictions) might cause endless imports, since each AJAX call would try to import these failing images over and over.

**Comment by donmhico** [comment]
This issue is resolved in #286 and will be included in the next release.
