### ISSUE TITLE
Check backwards compatibility with older WP versions

### ISSUE THREAD

**Issue by capuderg** [awesomemotive/one-click-demo-import#217]
WP.org ticket:
https://wordpress.org/support/topic/posts-and-pages-does-not-get-imported

Check if there are any issues with older WP versions: 4.9 and 5.2.

**Comment by yonkov** [comment]
I received Internal Error 500, when trying to import WP Import XML file on WordPress 5.2. I was able to import the xml by downgrading the plugin to version 2.5.2.

**Comment by capuderg** [comment]
Hi @yonkov,

could you please enable  WP debug + logging and run the import on WP 5.2 again? Then check the debug.log file in `wp-content` folder on your server after that?

More info about WP debugging can be found here: https://wordpress.org/support/article/debugging-in-wordpress/

So you would have to set `WP_DEBUG` and `WP_DEBUG_LOG` to `true`.

Let me know if any errors get logged to the debug file.

Thanks!

**Comment by capuderg** [comment]
This is fixed in the refresh-3.0 branch and will be available in the next big plugin update.

Connected to #230
