### ISSUE TITLE
Import seems to fail with Elementor 3.0+

### ISSUE THREAD

**Issue by SecondLineThemes** [awesomemotive/one-click-demo-import#218]
Hey @capuderg!

Seems like Elementor pages are failing with the importer since Elementor 3+
I know there was a patch last month but they seem to have changed something in the most recent update that breaks the imported pages.

To clarify - the importer can finalize the process without errors, but the imported data is corrupted.

**Comment by capuderg** [comment]
Hi @SecondLineThemes,

I've just tested an import with the latest Elementor and the latest version of OCDI and it looked OK. I used this theme: https://wordpress.org/themes/dr-life-saver/ as I did for the previous fix of elementor.

They did change something in the code in the `on_wxr_importer_pre_process_post_meta` method in the Compatibility class, but we are still removing it, so it should not be causing any issues.

What kind of problems do you experience with the import? Are you using the latest version of OCDI?

**Comment by SecondLineThemes** [comment]
Hi @capuderg, thanks for the swift reply.

Did some more debugging, and I think I found a solution.
When adding the following into the theme, the import process seems to pass correctly - 

`if ( method_exists( '\Elementor\Compatibility', 'on_wxr_importer_pre_process_post_meta' ) ) {
	remove_action( 'wxr_importer.pre_process.post_meta', array( 'Elementor\Compatibility', 'on_wxr_importer_pre_process_post_meta' ) );
	remove_filter( 'wxr_importer.pre_process.post_meta', array( 'Elementor\Compatibility', 'on_wxr_importer_pre_process_post_meta' ) );
}
`

You guys added the `remove_action` in the OCDI plugin itself, tried to place that in the theme + add the `remove_filter` and so far it looks okay.

Thanks again and sorry if this is not directly related to OCDI!

**Comment by capuderg** [comment]
Hi @SecondLineThemes,

The `remove_action` function also removes filters, since it is an alias for `remove_filter`: https://developer.wordpress.org/reference/functions/remove_action/#source

It's really strange that adding that resolved the issue for you. Are you sure you are using the latest version of OCDI (v2.6.1)?

Take care!

**Comment by SecondLineThemes** [comment]
Yeah I know, but perhaps adding both to the theme itself did something.
To be honest I don't remember if the `remove_action` alone did it or not.

I guess the main thing here is that it was added into a theme. No idea how that could have helped..

Basically I was testing Merlin WP with OCDI included in it. I tested both options (OCDI 2.6.1 alone and Merlin+OCDI).
They both failed before I've added the remove action/filter in the theme, but now both seem to work  🤷‍♂️

**Comment by capuderg** [comment]
The OCDI plugin is using a slightly modified importer with the Elementor fix. I don't think the Merlin WP does have the fix in it, since it's using the older importer...

**Comment by SecondLineThemes** [comment]
Of course, but it's a fork of Merlin with the most recent OCDI plugin. Either way - the issue also happened for me with just with the OCDI plugin, without any other plugins activated (just Elementor).

Again - not sure it's directly related to OCDI, could be theme related, but for some reason the above fix has worked

**Comment by vrabota** [comment]
I have same issue with latest Elementor 3.0.11 and Merlinwp. 
Demo content was imported but import data is corrupted (I can't edit pages with elementor it's a plain WordPress editor with some text).
Tested also Elementor 3.0.11 with latest One Click Demo Import 2.6.1 and can't upload my demo content at all. (Infinite loading screen)

@SecondLineThemes can you share with me fork link of Merlin with most recent OCDI plugin?

**Comment by capuderg** [comment]
Hi @vrabota,

I can only speak for One Click Demo Import (for issues with MerlinWP please contact their GH repo)...

Which version of WP and PHP is your site using? Also please follow the [debug/logging instructions here](https://github.com/awesomemotive/one-click-demo-import/issues/221#issuecomment-703696997) and let me know if you get any errors when you try to import the demo data.

Also, was the MerlinWP disabled when you tried to import the demo data with OCDI plugin? Please try that as well.

Take care!
