### ISSUE TITLE
Ok 200 Error

### ISSUE THREAD

**Issue by nizam7** [awesomemotive/one-click-demo-import#221]
I am getting ok 200 error while importing demo content in WordPress theme.

https://themeforest.net/item/car-repair-services-auto-mechanic-wordpress-theme/19823557

**Comment by nizam7** [comment]
Please help me.

**Comment by capuderg** [comment]
Hi,

which version of PHP and WP are you using on your site?

Please enable WP debugging and error logging and let me know what kind of errors you get when you are trying to import the demo content.

So follow these instructions to enable WP debug logging: https://www.wpbeginner.com/wp-tutorials/how-to-set-up-wordpress-error-logs-in-wp-config/

Then run the demo import again.

And report what kind of errors do you get.

Take care!

**Comment by capuderg** [comment]
I'm closing this GH issue because no additional data was provided.
