### ISSUE TITLE
Error: Internal Server Error (500)

### ISSUE THREAD

**Issue by KushnirDV** [awesomemotive/one-click-demo-import#222]
I am using WordPress 5.1
Running PHP version: 5.5.9-1ubuntu4.20

Server log:
PHP Fatal error:  Call to undefined function AwesomeMotive\WPContentImporter2\wp_slash_strings_only() in /path-to-wp/wp-content/plugins/one-click-demo-import/vendor/awesomemotive/wp-content-importer-v2/src/WXRImporter.php on line 1225

**Comment by pagelab** [comment]
> wp_slash_strings_only

This function is only present in [WordPress version 5.3 onwards](https://developer.wordpress.org/reference/functions/wp_slash_strings_only/).

So upgrading WordPress will solve the issue.

But, maybe you should also bump the required version, @capuderg?

Right now, the plugin page says: “Requires at least: 4.0”

**Comment by capuderg** [comment]
Hi!

Yes, this function is only available in WP version 5.3+.

We'll treat this as a bug and fix it in the next plugin update.

Thank you for reporting this issue!

**Comment by KushnirDV** [comment]
Hi!
Thanks for your answers. 
I have tried to upload some data with one-click-demo-import v2.6.1 and got the error mentioned above.
I decreased the version to v2.5.2 and successfully uploaded needed data.

**Comment by capuderg** [comment]
Yes, this function was added in the recent plugin version, for Elementor compatibility reasons.

Thanks for the info though! :)

**Comment by capuderg** [comment]
This was taken care of in another branch and will be fixed in the next plugin version.
