### ISSUE TITLE
Imports everything but still shows error

### ISSUE THREAD

**Issue by zamanq** [awesomemotive/one-click-demo-import#225]
Hi there,

The demo importer imports all the files successfully but then it shows the following error messages:

[ERROR] Failed to import "One Click Demo Import - log_file_2020-10-12__04-34-36" (Media)
[ERROR] Failed to import "One Click Demo Import - log_file_2020-10-12__04-49-03" (Media)

I checked, all the files, customizer settings and widgets got imported successfully.

Any idea why is that happening?

**Comment by capuderg** [comment]
Hi!

please check your XML import file and see if the above two files are present in it. If they are and you deleted those files on your server, then they can't be imported and so they fail. 

The solution: clean up the import XML file, to remove those two file's XML code.

Take care!
