### ISSUE TITLE
Import is working well but the page look messy

### ISSUE THREAD

**Issue by LOCRICCHIO** [awesomemotive/one-click-demo-import#226]
Hi,

I just setup up the plugin and add .xml / .wie and .dat but when the import is finished, the page look messy, there is no style.

Look at my attchement. Where could be the problem ?

Thanks !

![image](https://user-images.githubusercontent.com/52154727/99498732-37910f80-2978-11eb-86ed-a0bce74254eb.png)

**Comment by capuderg** [comment]
Hi @LOCRICCHIO,

did you install the required plugins before importing the demo content?

Maybe some plugins are used (like pagebuilders) to keep the content layout?

Take care!

**Comment by LOCRICCHIO** [comment]
Thanks a lot ! It was the issue, one plugin wasnt activate.

Thanks you !
