### ISSUE TITLE
Import taxonomies

### ISSUE THREAD

**Issue by sinashamsizadeh** [awesomemotive/one-click-demo-import#227]
Hi,
I tried import Woocommerce, post, and custom post type with some taxonomies like category, tag, product_cat, product_tag and product_attributes but seems there is an issue with import the taxonomies. in all above post types one click demo import can’t import taxonomies

**Comment by capuderg** [comment]
Hi!

Did you have the custom post type's taxonomies registered when you imported the content?

The custom post type's posts were imported OK, just the taxonomies were not? And the taxonimies are registered when the import was made?

Take care!

**Comment by sinashamsizadeh** [comment]
I have good news for you, I figured out when it occurs!
When you export "All content" everything (including all taxonomies in all the post types) will import successfully but when you export just one item, like "posts" or any other post type like "Woocommerce Products", the one click importe cannot import the taxonomies for the post type. See the below screenshot:
https://prnt.sc/vt2fmr
I hope my report will prove useful to you in fixing this bug.

Yes, I'm sure about the registration. I was only able to find the other issue mentioned above. Also, it is impossible to consider that when Woocommerce is installed products taxonomies is not registered. Or that WordPress default post cagetory and tag taxonomies is not registered. Correct?

All the best,

**Comment by capuderg** [comment]
If you export the content from a WP site with any filters, like "Posts", it will export only the post items, not the taxonomies or any other parts of your WP site.

Please compare the XML files from the export "All content" and "Posts" and you will see the "Posts" export XML file will not have any taxonomy items in it. So our plugin can't import any taxonomies if they are not present in the XML file.

Please let me know how it goes.

Take care!
