### ISSUE TITLE
PHP Warning for __wakeup

### ISSUE THREAD

**Issue by capuderg** [awesomemotive/one-click-demo-import#228]
WP.org ticket:
https://wordpress.org/support/topic/warning-message-showing-after-installation/

Fix this PHP Warning: 
Warning: The magic method OCDI\OneClickDemoImport::__wakeup() must have public visibility in C:\xampp\htdocs\wordpress\wp-content\plugins\one-click-demo-import\inc\OneClickDemoImport.php on line 128

And check with WP_DEBUG_LOG any other PHP warnings with newer versions of PHP.

**Comment by capuderg** [comment]
Resolved in https://github.com/awesomemotive/one-click-demo-import/commit/41c9195cb25c038bd985997ce7cbe75ee09cfd9e

**Comment by Khaledgy65** [comment]
Ok..Thanks a lot.
