### ISSUE TITLE
Undefined function wp_slash_strings_only

### ISSUE THREAD

**Issue by sinashamsizadeh** [awesomemotive/one-click-demo-import#230]
Hi,
I wanna report a fatal error in plugin

PHP Fatal error:  Call to undefined function AwesomeMotive\WPContentImporter2\wp_slash_strings_only() in /home/frb148364/domains/trytestcase.freecloudsite.com/public_html/wp-content/plugins/kata-plus/includes/importer/core/libraries/vendor/awesomemotive/wp-content-importer-v2/src/WXRImporter.php on line 1225

seems wp_slash_strings_only is deperecated
PHP version 5.6.x
https://developer.wordpress.org/reference/functions/wp_slash_strings_only/

**Comment by capuderg** [comment]
Hi @sinashamsizadeh,

which version of WP are you using? The error suggests it's lower than WP 5.3. In WP 5.6 (latest version) the function is still available, but deprecated, so the error would be different.

Thanks for reporting this issue. We'll fix it for the next plugin update.

Take care!

**Comment by capuderg** [comment]
This is fixed in the `refresh-3.0` branch and will be available in the next big plugin update.
