### ISSUE TITLE
como desfazer tais etapas?

### ISSUE THREAD

**Issue by patriciafrosas** [awesomemotive/one-click-demo-import#231]
Fiz todo o passo de instalação do plugin on-click-demo-import e dos arquivos de importação do Magazine Hoot (versão gratuita):
 - Dados do WordPress (.xml) (postagens, páginas, menus, imagens)
 - Configurações do personalizador (.dat)
 - Widgets (.wie)

Entretanto desconfigurou por completo o blog. Como desfazer (desinstalar) todas as etapas acima?!

**Comment by capuderg** [comment]
Hi @patriciafrosas,

there is no easy "undo" or "uninstall" process.

If this happened on a WP site with existing content and you want to get back to how it was before the import, the best option would be to restore your site from a backup (if you have one).

The other option is to delete the imported content and to reconfigure the theme customizer settings + widgets.

Take care!
