### ISSUE TITLE
2 taxonomies with the same term name slug

### ISSUE THREAD

**Issue by stormit** [awesomemotive/one-click-demo-import#232]
Hi,

We have found a probem with your plugin. We have 2 taxonomies: **product_cat** and **ts_product_brand**. Both have the same term named **Apply**. Please see my screenshots

[https://prnt.sc/10pl2q2](https://prnt.sc/10pl2q2)

[https://prnt.sc/10pl2zv](https://prnt.sc/10pl2zv)

And database we get after imported

[https://prnt.sc/10pl3tx](https://prnt.sc/10pl3tx)

[https://prnt.sc/10pl3w0](https://prnt.sc/10pl3w0)

As you can see, Apply (term_id = 155) is a **product_cat**. But, its parent is a **ts_product_brand**.

Please check and fix this issue!

Thank you!

**Comment by capuderg** [comment]
Hi @stormit,

thanks for reporting this issue.

Could you please provide the whole XML items (in text, not screenshot) for both of the items in question, so I can inspect it and try to reproduce the issue on my side?

Providing the whole XML import file would be even better.

Take care!
