### ISSUE TITLE
One click demo import plugin shows error

### ISSUE THREAD

**Issue by Khaledgy65** [awesomemotive/one-click-demo-import#233]
Hello, I am using this demo import plugin for many years. recently, It shows error with latest WordPress version. I tried and setup new but still faces error. **Kindly plugin authors help to fix this issue..**

**This warning:**

Warning: The magic method OCDI\OneClickDemoImport::__wakeup() must have public visibility in D:\xampp\htdocs\ennlil\wp-content\plugins\one-click-demo-import\inc\OneClickDemoImport.php on line 128

**Comment by Khaledgy65** [comment]
https://i.ibb.co/2sXLyQM/Screenshot-6.png

**Comment by capuderg** [comment]
Hi,

thanks for reporting this. We already fixed this in this GH issue https://github.com/awesomemotive/one-click-demo-import/issues/228

This appears if you use PHP 8.x.

This fix will be available in the next plugin update.

Thank you and have a nice day!

**Comment by Khaledgy65** [comment]
Can You please give me that updated file.

OneClickDemoImport.php

**Comment by capuderg** [comment]
Hi @Khaledgy65,

all you need to do is change `private` to `public` on the `private function __wakeup() {}` line, just like in this commit: https://github.com/awesomemotive/one-click-demo-import/commit/41c9195cb25c038bd985997ce7cbe75ee09cfd9e#

Take care!
