### ISSUE TITLE
Notice and Deprecated After Update 3.0.1

### ISSUE THREAD

**Issue by Pixelous** [awesomemotive/one-click-demo-import#235]
Hi,

After the update 3.0.1 on my multisite main site when 

`define( 'WP_DEBUG', true );`

I have the following:

**Notice**: Undefined index: menu_slug in **../wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php** on line **626**

**Deprecated**: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in **../wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php** on line **626**

**Notice**: Undefined index: menu_slug in **../wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php** on line **639**

**Deprecated**: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in **../wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php** on line **639**

Can you please fix it?

On my subsites it is ok, there are no such messages.

Kind regards

**Comment by capuderg** [comment]
Hi @Pixelous,

the OCDI v3.0.2 version was just released with this bug fix. Could you please install the plugin from the WordPress plugin repository and test it out.

Thank you and have a nice day!

**Comment by givan-extend** [comment]
Hi

After updating to v3.0.2 the plugin still shows the deprecated messages and import does not work.
Tested on php 7.4.16 and wordpress 5.7

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/***/public_html/wp/wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php on line 635

Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/***/public_html/wp/wp-content/plugins/one-click-demo-import/inc/OneClickDemoImport.php on line 652

**Comment by capuderg** [comment]
Hi @givan-extend,

I just tested with OCDI v3.0.2 with PHP 7.4.16 on a WP Multisite as well as on a normal WP site and did not get those deprecated notices and also the import worked just OK.

Could you please provide as many details about the actual import error you get? These deprecate notices are connected to parts of code that are not responsible for the actual import, so they shouldn't cause these issues.

Could you please let me know which theme you are using, so I could maybe try to test it out. Also, let me know if you are using WP Multisite or just a normal WP site.

@Pixelous did you had any actual issues with the import?
