### ISSUE TITLE
Import Demo Data Page

### ISSUE THREAD

**Issue by Pixelous** [awesomemotive/one-click-demo-import#236]
Hi,

Can you please add the possibility to rewrite Import Demo Data Page?

![image](https://user-images.githubusercontent.com/1421184/113224801-e2092f80-9294-11eb-82bc-7c466cfce5fc.png)

I have more than 20 demos and perhaps will add more so I would like to add lazy loading to screenshots.

Kind regards

**Comment by capuderg** [comment]
Hi @Pixelous,

you can already rewrite the whole plugin page, but I would discourage you from doing that. That would mean that you would have to update your implementation if we make any bigger changes to the plugin in the future...

You could overwrite the plugin page display function with this filter: `ocdi/plugin_page_display_callback_function` and hook your own display callback function. This means you would have to provide the code for the whole plugin page (predefined demo imports, manual imports, ...).

For more information on what you would have to do, I think it's best if you look into the default plugin page display method: `\OCDI\OneClickDemoImport::display_plugin_page`.

There are also other actions and filters throughout the plugin, that you might use, that have less of an impact and could still achieve what you want.

Take care!
