### ISSUE TITLE
Disable Plugins Page

### ISSUE THREAD

**Issue by Pixelous** [awesomemotive/one-click-demo-import#237]
Hi,

I would like to skip installing plugins step.

Can you please make this optional?

Kind regards

**Comment by DeoThemes** [comment]
I'm also looking for a solution to disable promoted plugins. Is there any way to override it?

**Comment by capuderg** [comment]
Hi,

thank you for contacting our support.

The Recommended Plugins step is an integral part of the import process for every WordPress theme. There are very few themes that don't rely on external plugins. These plugins have to be installed before the content can be successfully imported. What better way, to ensure that your theme's required and recommended plugins are installed, than just before the actual content import.

Please take a look at [our docs](https://ocdi.com/quick-integration-guide/) on how to add your theme recommended plugins to that step and allow your users to have a smooth experience importing your demo content.

We are always trying to improve our plugin, so we welcome any feedback, which could improve the experience of our end users.

Have a nice day!

**Comment by jaredatch** [comment]
Just wanted to reiterate what Gregor mentioned.

If you have any insights please let us know.

We've worked really hard to make OCDI an important and useful tool for theme authors, but that means getting direct feedback and ideas from theme authors :)

**Comment by DeoThemes** [comment]
Please provide a filter to theme authors to opt-out from recommended plugins. The only way to remove it now is via JS.
