### ISSUE TITLE
Version 3.0.0 broke existing links to Import page

### ISSUE THREAD

**Issue by anastis** [awesomemotive/one-click-demo-import#238]
The Import Demo Data page used to live under `/wp-admin/themes.php?page=pt-one-click-demo-import`, however v3.0.0 changed the slug to `one-click-demo-import`, making all existing links show the dreaded `Sorry, you are not allowed to access this page.` message screen.

I understand the rename may have been necessary for branding reasons, however you may want to consider adding support for backwards compatibility, even if it is a simple redirection with a deprecation warning.

Just us, we have more than 40 themes that point to that old page via our own onboarding screen. While we will certainly release updates in the coming days to fix the issue for our users, you probably want to seriously consider the impact this issue might have to countless other themes out there.

**Comment by capuderg** [comment]
Hi @anastis,

thank you very much for reporting this issue. I've already fixed the issue in code, but I'm not 100% sure when the 3.0.2 will be released (don't have an exact date/time right now).

If you could test (edit the plugin with the above code changes) this fix posted in the above commit, that would be awesome! 

Take care!

**Comment by anastis** [comment]
Hi @capuderg,

yes! It works beautifully.

**Comment by capuderg** [comment]
Hi @anastis,

the OCDI v3.0.2 version was just released with this bug fix. Could you please install the plugin from the WordPress plugin repository and test it out.

Thank you for reporting and testing this issue. 🥳 

Have a nice day!

**Comment by anastis** [comment]
Hi @capuderg,

works like a charm!

Thank you for your prompt replies and response to this issue.
