### ISSUE TITLE
Make successful import buttons filterable

### ISSUE THREAD

**Issue by capuderg** [awesomemotive/one-click-demo-import#239]
Allow theme authors to define after import buttons on the success screen with the default being the customizer and front page buttons. Also, provide them with a filter for some custom text in the success screen content.

User feedback:
> After importing demo content there are two buttons visit site and theme settings. It would be better if we(the developer ) has a little control over this. Meaning the visit site and theme settings should open in a new tab ( just my thought ). And theme settings may always not be the customizer. If I am using Elementor page builder I would like to redirect to the Elementor settings, not the customizer settings.

**Comment by capuderg** [comment]
One more request for this feature: https://wordpress.org/support/topic/theme-settings-button/

**Comment by ravishakya** [comment]
Hi,

One more thing I would like to add here. Most of the users don't even click the buttons. It would be great if we the theme authors have the ability to redirect to a specific URL after a successful import. Normally that URL would be the theme settings page ( Customizer/ Elementor page .... etc )

Thank You

**Comment by donmhico** [comment]
This issue is resolved with #280. We will include this in our next release. Thank you to everyone who participated in this issue!
