### ISSUE TITLE
Remove recommended plugins by OCDI

### ISSUE THREAD

**Issue by idesignzone** [awesomemotive/one-click-demo-import#247]
Hi. Hope you are doing well. 

"The plugins with * icon are recommended by One Click Demo Import plugin to help you grow your website. They are not required for the ... theme to work."

I'm developing a headless solution and these plugins are not compatible with my theme. 
is there any hook to remove these plugins and notification?

Thank you.

**Comment by capuderg** [comment]
Hi @idesignzone,

no, there is no way to programmatically remove these 3 recommended plugins from that step. These 3 plugins are not pre-selected and the user has to select them first in order to install them. So, if the user just ignores them, they will not be installed by default.

Take care!
