### ISSUE TITLE
max mega menu 

### ISSUE THREAD

**Issue by yash19070** [awesomemotive/one-click-demo-import#255]
hello
i develop custom WordPress theme and using wp max mega menu plugin 
when importing demo data with ocdi its fine but not importing mega menu data and settings also 
is there any hook or tweak available 

thank you

**Comment by capuderg** [comment]
Hi @yash19070,

you'll have to import your mega menu settings after the demo import is finished. Please read our [docs for after import hook](https://ocdi.com/advanced-integration-guide/#after-import-custom-code-execution).

So, using the `ocdi/after_import` hook, you should execute the mega menu settings configuration.

Note: imported menu items will most probably have different IDs than your original demo site, so keep that in mind if you have to select and configure some menus based on the ID. It's best to use `get_term_by` to get the menu object and get the ID from it. Just like we show in the example in the doc page linked above.
