### ISSUE TITLE
Recommended Plugins page: Update WPForms active install count to 5,000,000+

### ISSUE THREAD

**Issue by ethanchoi812** [awesomemotive/one-click-demo-import#256]
On the Recommended Plugins page (Import Demo Data > Recommended Plugins) "Join 4,000,000+ professionals who build smarter forms and surveys with WPForms." https://a.supportally.com/5sVIQo

The current number should be 6,000,000+ now :)

**Comment by donmhico** [comment]
Thank you for creating this issue @ethanchoi812. I've resolved this in https://github.com/awesomemotive/one-click-demo-import/commit/7f3c6826281f52c5660f082d3efba504aaaa9aa1 and will be included in our next release. 🙇
