### ISSUE TITLE
Woocommerce shop page duplicate issue 

### ISSUE THREAD

**Issue by mihir1337** [awesomemotive/one-click-demo-import#257]
When I try to import data for the WordPress theme I got a Shop page in the menu with the slug of "shop-2", But the actual slug should be only "shop". woocommerce by default generates those pages but I want only to import the page I create and export and import with OCDI.
Here you can see after importing demo data I have a page with the slug of 'shop-2' which should be only 'shop' this page is set in my theme menu but it's messed up the link. how can I solve this?
![download](https://user-images.githubusercontent.com/26067204/160604184-9d1b1c4a-e1f3-47e7-bd2b-1439c551b257.png)

**Comment by capuderg** [comment]
Hi @mihir1337,

If you would prefer the your Shop page (the one that is imported) and other WC pages that you import, then you would have to prevent WC to generate the default pages. I'm sure there is a filter in WC to disable that on plugin activation.

Once you disable the default WC pages generation, you would then also have to set the WC pages you import in the WC settings. You can do that with some custom code and our [after import hook](https://ocdi.com/advanced-integration-guide/#after-import-custom-code-execution). You just need to write the custom code to set the imported pages as the WooCommerce shop, cart, checkout, and account pages.

As you see, some custom coding is involved, but it should be possible to make it work as you wish.

Take care!

Take care!

**Comment by mihir1337** [comment]
@capuderg Thanks for yours.
Unfortunately, I didn't find any options for preventing WC auto pages generation.
Can you please let me know if you found any?

**Comment by capuderg** [comment]
With a quick search of the WC code, I could find this filter: `woocommerce_create_pages`.

I think if you hook into this filter and return an empty array, no pages will be generated on WC plugin activation.

Take care!

**Comment by mihir1337** [comment]
@capuderg I use the filter and return an empty array it quite does the job but shows an error in wp-dashboard 
![image](https://user-images.githubusercontent.com/26067204/161945326-2d8002ce-8fa8-45ba-9135-7cb820622d95.png)

Like this one 
![image](https://user-images.githubusercontent.com/26067204/161945481-d7e36c6e-7528-43fb-801f-c4daeae96a8f.png)

Also got this one 
![image](https://user-images.githubusercontent.com/26067204/161945526-bc029557-00b8-4cab-88ab-0fa5958fb085.png)

The error only shows one time when I try to activate woocomerce plugin and import demo data, but if I try to do it again it works fine.

**Comment by mihir1337** [comment]
@capuderg  I got some reply from woocomerce itself too.
![image](https://user-images.githubusercontent.com/26067204/161946097-40ec35e7-d143-4659-b687-52b9e143bb48.png)

**Comment by capuderg** [comment]
Hi @mihir1337,

you can't use the same filter as inside the filter callback... Replace all your above code with this line:
`add_filter('woocommerce_create_pages', '__return_empty_array');`

Let me know how that goes.

**Comment by mihir1337** [comment]
@capuderg  It does kinda work but After I import demo data checkout and cart page are not set as they should be
you can check the ss https://prnt.sc/84R0eAk6uuJ5

Is there any way I can only stop the 'shop' page to recreate it?

**Comment by mihir1337** [comment]
@capuderg 
For the home page and blog page, we have those two options 
![image](https://user-images.githubusercontent.com/26067204/162744457-1f6146e8-7cc6-4d8b-9e51-884007c4f5a2.png)

Is there anything similar for the cart page and checkout page?
![image](https://user-images.githubusercontent.com/26067204/162744598-67578602-95f2-45ab-892a-789bde7e5e3a.png)

**Comment by mihir1337** [comment]
@capuderg  Thanks for your help.
The issue is finally solved. 
Really appreciate your support

**Comment by capuderg** [comment]
I'm glad you resolved it. 👍 

Have a nice day!

**Comment by eriktailor** [comment]
> @capuderg Thanks for your help. The issue is finally solved. Really appreciate your support

Can you share the final solution with us? Thanks :)

**Comment by namagrap** [comment]
Hello
I spent some time for the solution and I will post it for you.

$woocommerce_shop  = get_page_by_title( 'Products' );
$woocommerce_checkout  = get_page_by_path( 'checkout-2' );
$woocommerce_cart  = get_page_by_path( 'cart-2' );
$woocommerce_myaccount  = get_page_by_path( 'myaccount-2' );

update_option( 'woocommerce_cart', $woocommerce_cart->ID );
update_option( 'woocommerce_checkout_page_id', $woocommerce_checkout->ID );
update_option( 'woocommerce_cart_page_id', $woocommerce_cart->ID );
update_option( 'woocommerce_myaccount_page_id', $woocommerce_myaccount->ID );
update_option( 'woocommerce_shop_page_id', $woocommerce_shop->ID );

**Comment by namagrap** [comment]
for the title :  get_page_by_title
for slug :  get_page_by_path

**Comment by Prashant-96** [comment]
I have faced the same issue. Can you share the final solution with us? Thanks.
