### ISSUE TITLE
PHP Warning:  Array to string conversion

### ISSUE THREAD

**Issue by hogash** [awesomemotive/one-click-demo-import#266]
Hi guys,

Getting this error `PHP Warning:  Array to string conversion in /../plugins/one-click-demo-import/vendor/awesomemotive/wp-content-importer-v2/src/WXRImporter.php on line 1906` .

So basically the `$value` at https://github.com/awesomemotive/WordPress-Importer/blob/master/src/WXRImporter.php#L1906 is expected to be a string, but there are cases when it's an array. 

I propose replacing `$value` with `is_array($value) ? wp_json_encode($value) : $value` to stringify it.

**Comment by donmhico** [comment]
Thank you for reporting this issue. This was fixed in #290 and will be included in the next release.
