### ISSUE TITLE
do you have any hook for remove theme name, screenshot on plugin page ??

### ISSUE THREAD

**Issue by ThemeOri** [awesomemotive/one-click-demo-import#272]
like https://prnt.sc/tdxh5uOTJSVR

this section I want to remove this from the plugin page because I already did a custom demo import below this sections.

like add_filter('ocdi/plugin_intro_text', '__return_false');    its work before this section text remove but for this section i cant find any hook yet ?

**Comment by capuderg** [comment]
Hi,

I'm sorry, but there is no such hook. This section just shows the current active theme' info and the screenshot.

You could however overwrite the whole plugin page display callback function with this filter: `ocdi/plugin_page_display_callback_function`.

The default callback function is `\OCDI\OneClickDemoImport::display_plugin_page`, so you can take a look how it works and  you can then copy different "views" from the plugin and changing them in your theme (and load those instead).

Take care!
