### ISSUE TITLE
Images Lazy Loading

### ISSUE THREAD

**Issue by Pixelous** [awesomemotive/one-click-demo-import#273]
Hi,

Can you please add `loading="lazy"` attribute for images?

Kind regards

**Comment by Pixelous** [comment]
@capuderg these that are on importing page

![image](https://user-images.githubusercontent.com/1421184/222987231-6a606f12-1d65-480f-8281-61e5471eeb23.png)

Kind regards

**Comment by donmhico** [comment]
This issue has been resolved in #289 and will be included in the next release. Thanks for creating the issue @Pixelous!
