### ISSUE TITLE
Fix PHP Deprecated notice for ReduxFramework integration

### ISSUE THREAD

**Issue by capuderg** [awesomemotive/one-click-demo-import#277]
> This plugin throwing the Deprecated notice after the import, It related to ReduxFramework plugin. Here it the notice.
> PHP Deprecated: Function set_options is deprecated since version 4.0.0! Use options_class->set( $value ) instead. in K:\wamp64\www\kyber\wp-includes\functions.php on line 5413

original post: https://wordpress.org/support/topic/php-deprecated-notice-7/

**Comment by donmhico** [comment]
This issue is resolved in #281 and will be included in our next release. Thanks for creating this issue!
