### ISSUE TITLE
Importing customizer settings

### ISSUE THREAD

**Issue by speeedsam** [awesomemotive/one-click-demo-import#282]
---Importing customizer settings---
Error: The customizer import file is not suitable for the current theme. You can only import customizer settings for the same theme or a child theme. 

This error got it when import demo.

**Comment by donmhico** [comment]
Hello,

This issue means that the customer settings were exported from a different theme compared to the theme installed in the WordPress site where it was imported.

May I ask what theme was installed and activated on your site when you performed the import and what theme demo you were trying to import?

**Comment by donmhico** [comment]
Hello,

I'm closing this issue since we haven't heard back from you. Please feel free to re-open if you are still experiencing this issue.
