### ISSUE TITLE
Support WPForms import

### ISSUE THREAD

**Issue by donmhico** [awesomemotive/one-click-demo-import#291]
## Description

Support WPForms import like how Redux Framework is supported.

## Reference

https://wordpress.org/support/topic/wp-forms-import/

**Comment by ecobeesBibhushan** [comment]
Is it being worked on?

**Comment by ecobeesBibhushan** [comment]
Can we import any other forms using this plugin?
@donmhico

**Comment by capuderg** [comment]
Hi @ecobeesBibhushan,

for now there are no forms integrations in OCDI plugin, but you can execute custom code at the end of the import process. You can hook into this WP action: https://ocdi.com/advanced-integration-guide/#after-import-custom-code-execution and implement the forms import if your forms plugin allows you to do that via code.
