### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by foundanand** [awesomemotive/one-click-demo-import#293]
I am getting this error while uploading this plugin from wordpress.org

**Comment by capuderg** [comment]
Hi @foundanand could you please provide more info about the error message you receive, so we can try to debug it?

Maybe enabled WP Debug Log mode can help to get the full error message: https://www.wpbeginner.com/wp-tutorials/how-to-easily-enable-wordpress-debug-mode-to-fix-site-errors/

**Comment by foundanand** [comment]
> Hi @foundanand could you please provide more info about the error message you receive, so we can try to debug it?
> 
> Maybe enabled WP Debug Log mode can help to get the full error message: https://www.wpbeginner.com/wp-tutorials/how-to-easily-enable-wordpress-debug-mode-to-fix-site-errors/

While uploading the plugin it shows fatal error occurred while trying to add this plugin. I will try the enabled method and update you!

**Comment by foundanand** [comment]
The issue was with one of the other plugins, I reinstalled all and it was fixed
