### ISSUE TITLE
Idea - Develop complimentary plugin that saves all required import files to a specific folder

### ISSUE THREAD

**Issue by BoweFrankema** [awesomemotive/one-click-demo-import#38]
Hi guys,

Lovely plugin idea and execution, I'm playing around with it now! I have one idea that I think would really help with the workflow for theme developers. Here's a proposed workflow I'd love to see for this plugin:
1. You start out with a multisite installation for your theme.
2. You set up a WordPress installation where every subsite is a one click demo install. You configure it as you see fit with menus, widgets, theme options etc.
3. Once you are happy with your demo (or want to update the existing one) you click on a button in the WordPress admin bar "Generate One Click Demo files". 
4. The xml, json and .dat files are automatically generated and saved into a publicly accessible folder. (ea. http://myinstallation.com/demo-one/uploads/one-click-demo/content.xml).
5. Now your demo is updated!

Ideally this could be achieved by filters/actions available in the various plugins, but to be honest I'm not sure how hard that would be.

I'm curious what other people think about this idea and thanks again for the hard work on this!

**Comment by capuderg** [comment]
Hi,

thanks :)

We were thinking about something similar, but we have to finish this plugin first and then see what we'll do next. I've been a bit behind schedule, so I hope I can completely finish the plugin till the end of summer.

Thanks for your input and let's see, if others have some additional ideas. Maybe a bit different workflow?

Take care!

**Comment by nicolas92** [comment]
It's a great idea :+1:
Only one plugin to export all files instead of three plugins.

**Comment by capuderg** [comment]
We are working on this project, so it should be ready in a couple of weeks.

**Comment by BoweFrankema** [comment]
Amazing news! Let me know if you need any help with testing :-)

**Comment by capuderg** [comment]
Hi,

as you can see from the discussion date, the export plugin project was not finished and there are no current plans to create it. I'll close this GH issue.
